"""add pressure table

Revision ID: 369c4cb52100
Revises: 8ee22608dfaa
Create Date: 2024-05-10 02:18:38.006509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369c4cb52100'
down_revision: Union[str, None] = '8ee22608dfaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pressure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PressureSensorID', sa.Integer(), nullable=False),
    sa.Column('Pressure', sa.Float(), nullable=True),
    sa.Column('DateTimeOfMeasure', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['PressureSensorID'], ['GDS_Pressure.PressureSensorID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pressure')
    # ### end Alembic commands ###
