"""add temperature table

Revision ID: 8ee22608dfaa
Revises: 8a274de2e96d
Create Date: 2024-05-10 02:17:45.159793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee22608dfaa'
down_revision: Union[str, None] = '8a274de2e96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TempSensorID', sa.Integer(), nullable=False),
    sa.Column('Temperature', sa.Float(), nullable=True),
    sa.Column('DateTimeOfMeasure', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['TempSensorID'], ['GDS_Temperature.TempSensorID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Temperature')
    # ### end Alembic commands ###
