"""initial

Revision ID: a30f5f27142b
Revises: 
Create Date: 2024-05-08 00:58:25.773959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30f5f27142b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GDS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GDS_ID', sa.Integer(), nullable=False),
    sa.Column('RegionID', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('GDS_ID')
    )
    op.create_table('GDS_Temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GDS_ID', sa.Integer(), nullable=False),
    sa.Column('TempSensorID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GDS_ID'], ['GDS.GDS_ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GDS_Temperature')
    op.drop_table('GDS')
    # ### end Alembic commands ###
